version: '3.9'

services:
  database:
    image: postgres:16.1-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./images/postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - internal_local_network
      - default

  tima_backend:
    build:
      context: ./images/tima_backend
      dockerfile: Dockerfile
    container_name: tima_backend
    image: tima_backend
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./images/tima_backend:/home/app/web
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - /var/www/static:/var/www/static
      - /var/certbot/conf:/etc/letsencrypt/:ro
    environment:
      - VIRTUAL_HOST=${API_VIRTUAL_HOST}
      - VIRTUAL_PORT=${API_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${API_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    stdin_open: true
    tty: true
    networks:
      - internal_local_network
      - default

  tima_frontend:
    build:
      context: ./images/tima_frontend
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local  # or production
    container_name: tima_frontend
    image: tima_frontend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - tima_backend
    volumes:
      - ./images/tima_frontend/public:/home/app/web/public
      - ./images/tima_frontend/app:/home/app/web/app
      - ./images/tima_frontend/next.config.js:/home/app/web/next.config.js
      - ./images/tima_frontend/tailwind.config.ts:/home/app/web/tailwind.config.ts
      - ./images/tima_frontend/tsconfig.json:/home/app/web/tsconfig.json
      - ./images/tima_frontend/.yarnrc.yml:/home/app/web/.yarnrc.yml
      - ./images/tima_frontend/package.json:/home/app/web/package.json
      - ./images/tima_frontend/yarn.lock:/home/app/web/yarn.lock
      - /var/www/static:/var/www/static
      - /var/certbot/conf:/etc/letsencrypt/:ro
    environment:
      - VIRTUAL_HOST=${FRONTEND_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${FRONTEND_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    stdin_open: true
    tty: true
    networks:
      - internal_local_network
      - default

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /etc/nginx/conf.d
    labels:
    - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    - "VIRTUAL_HOST=cybelimited.com"
    - "LETSENCRYPT_HOST=cybelimited.com"

    networks:
      - internal_local_network
      - default

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  vhost:
  html:

networks:
  default:
  internal_local_network:
    driver: bridge
